### ISSUE TITLE
I am getting No module named 'cgelib' error

### ISSUE THREAD

**Issue by sankadinesh** [cadms/resfinder#4]
python3 run_resfinder.py -ifq /Users/apple/resfinder/tests/data/test_isolate_01_1.fq -o  /Users/apple/resfinder -k /Users/apple/resfinder/db_resfinder/kma -db_res /Users/apple/resfinder/db_resfinder 
Traceback (most recent call last):
  File "run_resfinder.py", line 10, in <module>
    from cgelib.output.result import Result
ModuleNotFoundError: No module named 'cgelib'
(base) APPLEs-MBP-6:resfinder Dinesh$ python3 run_resfinder.py
Traceback (most recent call last):
  File "run_resfinder.py", line 10, in <module>
    from cgelib.output.result import Result
ModuleNotFoundError: No module named 'cgelib'

Please help
Dinesh

**Comment by rebecca482** [comment]
Did you find a solution to this issue? I'm currently facing the same problem.

**Comment by cabeaudoin** [comment]
the following worked for me:
`pip3 install cgelib`
and then I also had to run this afterwards
`pip3 install resfinder`
all of that being after the suggested steps
