### ISSUE TITLE
Install test failure

### ISSUE THREAD

**Issue by josephhughes** [cadms/resfinder#5]
Hi,

I'm getting this error on running the install tests. Any advice would be most welcome

```
python3 tests/functional_tests.py
/home1/jh212a/bin/resfinder/cge/pointfinder.py:1277: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if mut_name is "p.V940delins - Frame restored":
E.EE
======================================================================
ERROR: test_on_data_with_just_acquired_resgene_using_blast (__main__.ResFinderRunTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/functional_tests.py", line 93, in test_on_data_with_just_acquired_resgene_using_blast
    procs = run(cmd_acquired, shell=True, stdout=PIPE, stderr=PIPE,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3  /home1/jh212a/bin/resfinder/run_resfinder.py -ifa data/test_isolate_01.fa -o running_test/test1 -s 'Escherichia coli' --min_cov 0.6 -t 0.8 --acquired --db_path_res /home1/jh212a/bin/resfinder/db_resfinder --blastPath /home1/jh212a/bin/resfinder/cge/blastn' returned non-zero exit status 1.

======================================================================
ERROR: test_on_data_with_just_point_mut_using_blast (__main__.ResFinderRunTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/functional_tests.py", line 209, in test_on_data_with_just_point_mut_using_blast
    procs = run(cmd_point, shell=True, stdout=PIPE, stderr=PIPE,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 /home1/jh212a/bin/resfinder/run_resfinder.py -ifa data/test_isolate_05.fa -o running_test/test3 -s 'Escherichia coli' --min_cov 0.6 --threshold 0.8 --point --db_path_point /home1/jh212a/bin/resfinder/db_pointfinder --db_path_res /home1/jh212a/bin/resfinder/db_resfinder --blastPath /home1/jh212a/bin/resfinder/cge/blastn' returned non-zero exit status 1.

======================================================================
ERROR: test_on_data_with_just_point_mut_using_kma (__main__.ResFinderRunTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/functional_tests.py", line 253, in test_on_data_with_just_point_mut_using_kma
    procs = run(cmd_acquired, shell=True, stdout=PIPE, stderr=PIPE,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python3 /home1/jh212a/bin/resfinder/run_resfinder.py -ifq data/test_isolate_05_1.fq data/test_isolate_05_2.fq -o running_test/test4 -s 'Escherichia coli' --min_cov 0.6 --threshold 0.8 --point --db_path_point /home1/jh212a/bin/resfinder/db_pointfinder --db_path_res /home1/jh212a/bin/resfinder/db_resfinder --kmaPath /home1/jh212a/bin/resfinder/cge/kma/kma' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 4 tests in 2.413s

FAILED (errors=3)

```

**Comment by Sinceter** [comment]
Hi, I am having the same errors like yours. Any progress on this? 

Kind regards :)

**Comment by pjbiggs** [comment]
Hi there, I am too. I am using python 3.12 in conda, and python 3.8 outside of conda, and I am getting the failure in both. Some help would be greatly appreciated. Thanks.
