### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableSet'

### ISSUE THREAD

**Issue by imonteroo** [cadms/resfinder#8]
I have Resfinder installed in a Conda environment and whe I run it I have this error 

`run_resfinder.py -o /media/microviable/SeagateExpansion/Biobakery_Results/Ser02-ABBiotics_E_rarefied/Resfinder -l 0.6 -t 6 --acquired --point -s "Other" -ifq /media/microviable/SeagateExpansion/Biobakery_Results/Ser02-ABBiotics_E/kneaddata/main/
Traceback (most recent call last):
  File "/home/microviable/bin/run_resfinder.py", line 8, in <module>
    from cge.resfinder import ResFinder
  File "/home/microviable/Programas/resfinder/cge/resfinder.py", line 14, in <module>
    from .output.table import TableResults
  File "/home/microviable/Programas/resfinder/cge/output/table.py", line 2, in <module>
    from .orderedset import OrderedSet
  File "/home/microviable/Programas/resfinder/cge/output/orderedset.py", line 20, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'`

**Comment by Sinceter** [comment]
Yea, me the same error...

**Comment by pjbiggs** [comment]
Yes, me too, though my errors are for the running of `functional_tests.py`. I am using python 3.12 in conda, and python 3.8 outside of conda, and I am getting the failure in both.   Some help would be greatly appreciated.  thanks.  for example:

`XXXX@XXX:resfinder$ python3 tests/functional_tests.py`
`Traceback (most recent call last):`
`  File "../run_resfinder.py", line 8, in <module>`
`    from cge.resfinder import ResFinder`
`  File "/home/pbiggs/software/resfinder/cge/resfinder.py", line 9, in <module>`
`    from tabulate import tabulate`
`ModuleNotFoundError: No module named 'tabulate'`
`EEEE`
`======================================================================`
`ERROR: test_on_data_with_just_acquired_resgene_using_blast (__main__.ResFinderRunTest)`
`----------------------------------------------------------------------`
`Traceback (most recent call last):`
`  File "tests/functional_tests.py", line 72, in test_on_data_with_just_acquired_resgene_using_blast`
`    procs = run("python3 ../run_resfinder.py -h", shell=True, stdout=PIPE,`
`  File "/usr/lib/python3.8/subprocess.py", line 516, in run`
`    raise CalledProcessError(retcode, process.args,`
`subprocess.CalledProcessError: Command 'python3 ../run_resfinder.py -h' returned non-zero exit status 1.`

**Comment by MargauxLefebvre** [comment]
I had the same error because my conda environment for ResFinder was with Python v3.14.6. Changing to Python v3.9 solved the problem. Maybe it should be specified in the "Installation" part.
